# Generated by Django 5.2 on 2025-04-08 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_administrador',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_chef',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_manutentor',
        ),
    ]
